In [59]:
import torch

In [60]:
#AI_머신러닝_딥러닝_개발 #미니실습

# 텐서 , 기본 함수 확인
#
# 📌 문제 1: PyTorch에서 랜덤 텐서를 생성하고, 가장 큰 값을 가진 인덱스를 찾으세요.
# (1) 4x4 크기의 랜덤 텐서를 생성하세요.
tensor = torch.rand(4,4)
print(f"tensor: {tensor}\n")

# (2) 각 행에서 가장 큰 값을 가진 인덱스를 찾으세요.
max = torch.argmax(tensor, dim=1)
print(f"max: {max}")

tensor: tensor([[0.7810, 0.2365, 0.3002, 0.4276],
        [0.5413, 0.4432, 0.6843, 0.6531],
        [0.6786, 0.6875, 0.1492, 0.3343],
        [0.0604, 0.9812, 0.6707, 0.0623]])

max: tensor([0, 2, 1, 1])


In [88]:
# 📌 문제 2: squeeze()와 unsqueeze()를 이용해 텐서의 차원을 조작하세요.
# (1) (1, 3, 1, 4) 크기의 랜덤 텐서를 생성하세요.
x = torch.rand(1, 3, 1, 4)
print("Original Tensor x:\n", x)
print(f"x.shape: {x.shape}\n")  # (1, 3, 1, 4)

# (2) squeeze()를 사용하여 크기를 줄이기
# - squeeze()는 크기가 1인 차원을 제거함
# - (1, 3, 1, 4) -> (3, 4) (차원 0과 2가 제거됨)
x_squeezed = x.squeeze()
print("Squeezed Tensor x_squeezed:\n", x_squeezed)
print(f"x_squeezed.shape: {x_squeezed.shape}\n")  # (3, 4)

# (3) unsqueeze()를 사용하여 특정 차원에 새 차원 추가
# - unsqueeze(dim=1)은 지정한 위치(dim=1)에 차원을 추가
# - (3, 4) -> (3, 1, 4) (차원 1이 추가됨)
x_unsqueezed = x_squeezed.unsqueeze(1)
print("Unsqueezed Tensor x_unsqueezed:\n", x_unsqueezed)
print(f"x_unsqueezed.shape: {x_unsqueezed.shape}")  # (3, 1, 4)

Original Tensor x:
 tensor([[[[0.5273, 0.5216, 0.6979, 0.0157]],

         [[0.8828, 0.6014, 0.5529, 0.9094]],

         [[0.9786, 0.8607, 0.2913, 0.9068]]]])
x.shape: torch.Size([1, 3, 1, 4])

Squeezed Tensor x_squeezed:
 tensor([[0.5273, 0.5216, 0.6979, 0.0157],
        [0.8828, 0.6014, 0.5529, 0.9094],
        [0.9786, 0.8607, 0.2913, 0.9068]])
x_squeezed.shape: torch.Size([3, 4])

Unsqueezed Tensor x_unsqueezed:
 tensor([[[0.5273, 0.5216, 0.6979, 0.0157]],

        [[0.8828, 0.6014, 0.5529, 0.9094]],

        [[0.9786, 0.8607, 0.2913, 0.9068]]])
x_unsqueezed.shape: torch.Size([3, 1, 4])


In [62]:
# 📌 문제 3: torch.cat()과 torch.stack()의 차이를 확인하세요.
# (1) 크기가 (2,3)인 두 개의 텐서를 만드세요.
# (1) 크기가 (2,3)인 두 개의 랜덤 텐서 생성
t1 = torch.rand(2, 3)
t2 = torch.rand(2, 3)

print(f"t1:\n{t1}")
print(f"t1.shape: {t1.shape}\n")

print(f"t2:\n{t2}")
print(f"t2.shape: {t2.shape}\n")

# (2) torch.cat()을 이용하여 dim=0 방향으로 연결
# - 기존 차원을 유지하면서 두 텐서를 연결
# - (2,3) + (2,3) -> (4,3)
tc = torch.cat((t1, t2), dim=0)
print(f"tc (Concatenated Tensor using torch.cat()):\n{tc}")
print(f"tc.shape: {tc.shape}\n")  # (4, 3)

# (3) torch.stack()을 이용하여 dim=0 방향으로 스택
# - 새로운 차원을 추가하여 두 텐서를 쌓음
# - (2,3), (2,3) -> (2,2,3)
ts = torch.stack((t1, t2), dim=0)
print(f"ts (Stacked Tensor using torch.stack()):\n{ts}")
print(f"ts.shape: {ts.shape}\n")  # (2, 2, 3)

t1:
tensor([[0.0200, 0.2132, 0.0360],
        [0.9555, 0.0060, 0.7800]])
t1.shape: torch.Size([2, 3])

t2:
tensor([[0.3882, 0.7285, 0.6654],
        [0.9849, 0.7056, 0.1483]])
t2.shape: torch.Size([2, 3])

tc (Concatenated Tensor using torch.cat()):
tensor([[0.0200, 0.2132, 0.0360],
        [0.9555, 0.0060, 0.7800],
        [0.3882, 0.7285, 0.6654],
        [0.9849, 0.7056, 0.1483]])
tc.shape: torch.Size([4, 3])

ts (Stacked Tensor using torch.stack()):
tensor([[[0.0200, 0.2132, 0.0360],
         [0.9555, 0.0060, 0.7800]],

        [[0.3882, 0.7285, 0.6654],
         [0.9849, 0.7056, 0.1483]]])
ts.shape: torch.Size([2, 2, 3])



In [71]:
# 📌 문제 4: torch.index_select()를 이용해 특정 행/열을 선택하세요.
# (1) 크기가 (4,4)인 랜덤 텐서를 생성하세요.
# (1) (4,4) 크기의 랜덤 텐서 생성
x = torch.randn(4, 4)  # 평균이 0이고 표준편차가 1인 정규분포에서 무작위 값 생성
print("Original Tensor x:\n", x)
print(f"x.shape: {x.shape}\n")  # (4, 4) 크기의 텐서

# (2) 첫 번째 열(인덱스 0)과 세 번째 열(인덱스 2)을 선택하여 새로운 텐서 생성
index = torch.tensor([0, 2])  # 선택할 열의 인덱스를 정의

# torch.index_select()를 사용하여 특정 열 선택
# dim=1: 열 기준으로 선택
s_columns = torch.index_select(x, dim=1, index=index)

print("Selected Columns:\n", s_columns)
print(f"s_columns.shape: {s_columns.shape}")  # (4, 2) 크기의 텐서 (4행 2열)

Original Tensor x:
 tensor([[ 1.2266,  0.4670,  0.7922,  0.1611],
        [-0.3993,  1.1065,  0.6036, -0.5090],
        [ 1.4561,  0.0553,  0.1083,  0.0616],
        [-0.6858, -0.6989,  0.3336,  1.9106]])
x.shape: torch.Size([4, 4])

Selected Columns:
 tensor([[ 1.2266,  0.7922],
        [-0.3993,  0.6036],
        [ 1.4561,  0.1083],
        [-0.6858,  0.3336]])
s_columns.shape: torch.Size([4, 2])


In [64]:
# 📌 문제 5: torch.topk()와 masked_fill()을 조합하여
# 특정 조건을 만족하는 값을 변경하세요.
# (1) 크기가 (3,5)인 랜덤 텐서를 생성하세요.
# (3,5) 크기의 랜덤 텐서 생성
x = torch.randn(3, 5)  # 평균이 0이고 표준편차가 1인 정규분포에서 값 생성
print("Original Tensor x:\n", x)
print(f"x.shape: {x.shape}\n")

# (2) 각 행에서 상위 3개의 값만 유지하고 나머지는 0으로 채우세요.
# torch.topk()는 각 행에서 가장 큰 k개의 값을 반환
# dim=1: 각 행에 대해 상위 k개 값 찾기, k=3
topk_values, topk_indices = torch.topk(x, k=3, dim=1)

# topk_values는 각 행의 상위 3개 값이 담긴 텐서, topk_indices는 해당 값들의 인덱스
print("Top 3 values (per row):\n", topk_values)
print("Top 3 indices (per row):\n", topk_indices)

# (3) masked_fill()을 이용하여 상위 3개를 제외한 값은 0으로 채우기
# 1. 텐서 x에서 상위 3개의 값의 인덱스를 찾아 0이 아닌 값으로 마스크 생성
mask = torch.zeros_like(x).scatter_(1, topk_indices, 1)

# 2. masked_fill()을 사용하여 마스크가 0인 부분을 0으로 채움
x_filtered = x * mask
print("Filtered Tensor (Top 3 values retained, others set to 0):\n", x_filtered)

Original Tensor x:
 tensor([[ 0.3906, -0.4124, -0.6856,  0.8934,  0.2775],
        [-0.5318, -0.6485, -0.6046, -0.8708, -0.1472],
        [-0.0507, -2.6268,  0.1717, -0.9101,  1.0915]])
x.shape: torch.Size([3, 5])

Top 3 values (per row):
 tensor([[ 0.8934,  0.3906,  0.2775],
        [-0.1472, -0.5318, -0.6046],
        [ 1.0915,  0.1717, -0.0507]])
Top 3 indices (per row):
 tensor([[3, 0, 4],
        [4, 0, 2],
        [4, 2, 0]])
Filtered Tensor (Top 3 values retained, others set to 0):
 tensor([[ 0.3906, -0.0000, -0.0000,  0.8934,  0.2775],
        [-0.5318, -0.0000, -0.6046, -0.0000, -0.1472],
        [-0.0507, -0.0000,  0.1717, -0.0000,  1.0915]])


In [73]:
# 📌 문제 6: torch.randperm()을 이용하여 데이터를 랜덤하게 섞은 후,
# torch.chunk()로 나누세요.
# (1) 10개의 원소를 가진 텐서를 0~9까지 숫자로 채우세요.
x = torch.arange(10)
print("Original Tensor x:\n", x)
print(f"x.shape: {x.shape}\n")

# (2) `torch.randperm()`을 사용하여 무작위로 섞으세요.
shuffled_x = x[torch.randperm(10)]
print("Shuffled Tensor:\n", shuffled_x)
print(f"shuffled_x.shape: {shuffled_x.shape}\n")

# (3) `torch.chunk()`를 사용하여 2개의 부분으로 나누세요.
chunks = torch.chunk(shuffled_x, 2)  # shuffled_x를 2개의 부분으로 나누기
print("Chunks:")
for i, chunk in enumerate(chunks):
    print(f"Chunk {i+1}:\n", chunk)

Original Tensor x:
 tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
x.shape: torch.Size([10])

Shuffled Tensor:
 tensor([9, 8, 1, 5, 2, 6, 0, 3, 7, 4])
shuffled_x.shape: torch.Size([10])

Chunks:
Chunk 1:
 tensor([9, 8, 1, 5, 2])
Chunk 2:
 tensor([6, 0, 3, 7, 4])


In [66]:
# 📌 문제 7: expand()를 사용하여 텐서 크기를 확장하세요.
# (1) 크기가 (1, 3)인 텐서를 생성하세요.
x = torch.randn(1, 3)  # 랜덤한 값으로 (1, 3) 크기의 텐서 생성
print("Original Tensor x:\n", x)
print(f"x.shape: {x.shape}\n")  # (1, 3)

# (2) `expand()`를 사용하여 (5, 3) 크기로 확장하세요.
# expand()는 텐서를 복제하는 것이 아니라 메모리 상에서 크기를 확장합니다.
y = x.expand(5, 3)  # x를 (5, 3) 크기로 확장
print("Expanded Tensor y:\n", y)
print(f"y.shape: {y.shape}\n")  # (5, 3)

Original Tensor x:
 tensor([[-0.3309, -1.8647, -0.4908]])
x.shape: torch.Size([1, 3])

Expanded Tensor y:
 tensor([[-0.3309, -1.8647, -0.4908],
        [-0.3309, -1.8647, -0.4908],
        [-0.3309, -1.8647, -0.4908],
        [-0.3309, -1.8647, -0.4908],
        [-0.3309, -1.8647, -0.4908]])
y.shape: torch.Size([5, 3])



In [82]:
# 📌 문제 8: split()과 chunk()의 차이를 이해하세요.
#
# (1) 크기가 (10,)인 1D 텐서를 생성하세요.
x = torch.arange(10)
print("원본 텐서:", x)

# (2) `split()`을 사용하여 3개의 텐서로 나누세요.
split_result = torch.split(x, [3, 3, 4])
print("split() 결과:", split_result)

# (3) `chunk()`을 사용하여 3개의 텐서로 나누세요.
chunk_result = torch.chunk(x, chunks=3)
print("chunk() 결과:", chunk_result)

원본 텐서: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
split() 결과: (tensor([0, 1, 2]), tensor([3, 4, 5]), tensor([6, 7, 8, 9]))
chunk() 결과: (tensor([0, 1, 2, 3]), tensor([4, 5, 6, 7]), tensor([8, 9]))


In [83]:
# 📌 문제 9: masked_fill()을 사용하여 특정 조건을 만족하는 요소를 변경하세요.
# (1) 크기가 (3, 3)인 랜덤 텐서를 생성하세요.
x = torch.rand(3, 3)
print("Original Tensor x:\n", x)

# (2) 값이 0.5보다 작은 요소를 -1로 변경하세요.
mask = x < 0.5  # 0.5보다 작은 값에 대해 True인 마스크 생성
x.masked_fill_(mask, -1)  # 마스크에 해당하는 값을 -1로 변경
print("Modified Tensor x:\n", x)

Original Tensor x:
 tensor([[0.0287, 0.7026, 0.2913],
        [0.0285, 0.2672, 0.4935],
        [0.6793, 0.7336, 0.9763]])
Modified Tensor x:
 tensor([[-1.0000,  0.7026, -1.0000],
        [-1.0000, -1.0000, -1.0000],
        [ 0.6793,  0.7336,  0.9763]])


In [86]:
# 📌 문제 10: torch.index_select()를 이용하여 특정 행을 선택하세요.
# (1) 크기가 (5, 4)인 랜덤 텐서를 생성하세요.
x = torch.rand(5, 4)
print("Original Tensor x:\n", x)

# (2) 두 번째와 네 번째 행만 선택하세요.
indices = torch.tensor([1, 3])  # 두 번째(1)와 네 번째(3) 행을 선택
selected_rows = torch.index_select(x, dim=0, index=indices)  # 행 선택
print("Selected Rows:\n", selected_rows)

Original Tensor x:
 tensor([[0.9492, 0.9942, 0.2774, 0.5485],
        [0.8533, 0.9286, 0.8313, 0.7795],
        [0.3764, 0.9364, 0.6860, 0.7413],
        [0.1099, 0.0583, 0.8902, 0.1953],
        [0.6952, 0.2392, 0.5410, 0.1727]])
Selected Rows:
 tensor([[0.8533, 0.9286, 0.8313, 0.7795],
        [0.1099, 0.0583, 0.8902, 0.1953]])
